# @package _global_
defaults:
  - override /backbone: clip_vision
  - _self_

model:
  _target_: models.arch.dtsh.DTSH
  backbone: ${backbone}
  has_adapter: True
  adapter_bottleneck_dim: 384
  nbit: 64
  nclass: ${dataset.nclass}

trainer:
  _target_: trainers.dtsh.DTSHTrainer

criterion:
  _target_: models.loss.dtsh.DTSHLoss
  alpha: 5
  lmbd: 1

backbone_lr_scale: 0
batch_size: 32
dataset:
  norm: 3

optim:
  lr: 0.001

epochs: 100