# @package _global_
defaults:
  - override /backbone: clip_vision
  - _self_

model:
  _target_: models.arch.hashnet.HashNet
  backbone: ${backbone}
  has_adapter: True
  adapter_bottleneck_dim: 384
  nbit: 64
  nclass: ${dataset.nclass}

trainer:
  _target_: trainers.hashnet.HashNetTrainer

criterion:
  _target_: models.loss.hashnet.HashNetLoss
  alpha: 1
  beta: 1
  step_continuation: ${epochs}
  train_size: 0
  keep_train_size: 0
  nbit: ${model.nbit}
  nclass: ${dataset.nclass}

backbone_lr_scale: 0
batch_size: 32
dataset:
  norm: 3

optim:
  lr: 0.001

epochs: 100