# @package _global_
defaults:
  - override /backbone: clip_vision
  - _self_

model:
  _target_: models.arch.semicon_ce.SEMICONCEWithAdapter
  backbone: ${backbone}
  nbit: 64
  nclass: ${dataset.nclass}
  has_adapter: True
  adapter_bottleneck_dim: 384
  loss_method: "ce"
  nattns: 4

trainer:
  _target_: trainers.semicon_ce.SEMICONCETrainer

criterion:
  _target_: models.loss.semicon_ce.SEMICONCELoss
  multiclass: ${dataset.multiclass}
  gamma: 0.001
  loss_method: ${model.loss_method}

backbone_lr_scale: 0
batch_size: 32
dataset:
  norm: 3

optim:
  lr: 0.001

epochs: 100
