# @package _global_

dataset:
  train_dataset:
    transform:
      - _target_: torchvision.transforms.RandomResizedCrop
        size: ${dataset.crop}
        interpolation:
          _target_: utils.transforms.interpolation
          _args_:
            - "bicubic"
      - _target_: torchvision.transforms.RandomHorizontalFlip
      - _target_: torchvision.transforms.ToTensor
      - _target_: utils.transforms.normalize_transform
        _args_:
          - ${dataset.norm}